/* Checks the TypeScript result maths against numpy.
 *
 * The fixture is generated by scripts/golden-quantum.py (run it from the
 * backend virtualenv). These are the numbers a learner reads off a Bloch
 * sphere, an entropy gauge or a phase table, so "close enough on my machine"
 * is not the standard: the port has to agree with the simulator's own maths to
 * 1e-9, and this is what catches a silently transposed qubit or a dropped
 * conjugate.
 *
 *   npx tsx scripts/golden-quantum.mts
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  amplitudes,
  blochAngles,
  blochVector,
  entanglementEntropy,
  probabilities,
  purity,
  qubitCount,
  reducedDensityMatrix,
  relativePhases,
} from "../src/lib/quantum.ts";

const fixturePath = fileURLToPath(new URL("../test-fixtures/quantum-golden.json", import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, "utf-8")) as {
  cases: {
    name: string;
    n_qubits: number;
    statevector: [number, number][];
    probabilities: number[];
    relative_phases: number[];
    purity: number;
    per_qubit: {
      qubit: number;
      x: number;
      y: number;
      z: number;
      theta: number | null;
      phi: number | null;
      entropy: number;
      purity: number;
    }[];
  }[];
};

const TOLERANCE = 1e-9;
let failures = 0;
let comparisons = 0;

function close(name: string, actual: number, expected: number) {
  comparisons += 1;
  const ok =
    (Number.isNaN(actual) && Number.isNaN(expected)) ||
    Math.abs(actual - expected) <= TOLERANCE;
  if (!ok) {
    failures += 1;
    console.log(`FAIL  ${name}: got ${actual}, expected ${expected}`);
  }
}

for (const testCase of fixture.cases) {
  const amps = amplitudes(testCase.statevector);
  if (!amps) {
    failures += 1;
    console.log(`FAIL  ${testCase.name}: statevector rejected`);
    continue;
  }

  close(`${testCase.name} qubit count`, qubitCount(amps), testCase.n_qubits);

  const probs = probabilities(amps);
  probs.forEach((p, i) => close(`${testCase.name} P(${i})`, p, testCase.probabilities[i]));

  relativePhases(amps).forEach((phase, i) =>
    close(`${testCase.name} phase(${i})`, phase, testCase.relative_phases[i]),
  );

  // The full-state purity is 1 by construction for every case here, so it
  // proves nothing; the per-qubit purities below are the real check.

  for (const expected of testCase.per_qubit) {
    const rho = reducedDensityMatrix(amps, testCase.n_qubits, expected.qubit);
    const [x, y, z] = blochVector(rho);
    close(`${testCase.name} q${expected.qubit} x`, x, expected.x);
    close(`${testCase.name} q${expected.qubit} y`, y, expected.y);
    close(`${testCase.name} q${expected.qubit} z`, z, expected.z);
    close(`${testCase.name} q${expected.qubit} entropy`, entanglementEntropy(rho), expected.entropy);
    close(`${testCase.name} q${expected.qubit} purity`, purity(rho), expected.purity);

    const { theta, phi } = blochAngles(x, y, z);
    if (expected.theta === null) {
      comparisons += 1;
      if (!Number.isNaN(theta)) {
        failures += 1;
        console.log(`FAIL  ${testCase.name} q${expected.qubit} theta should be NaN`);
      }
    } else {
      close(`${testCase.name} q${expected.qubit} theta`, theta, expected.theta);
      close(`${testCase.name} q${expected.qubit} phi`, phi, expected.phi);
    }
  }
}

console.log(
  failures === 0
    ? `ALL CHECKS PASSED — ${comparisons} values agree with numpy (1e-9)`
    : `${failures} of ${comparisons} VALUES DISAGREE`,
);
process.exit(failures === 0 ? 0 : 1);
