"""Record M4 lesson authoring progress in the tracker.

Usage:
    python m4_mark_lesson.py <lesson_slug> <topic_id> [status] [notes]

Marks the physical lesson and the target-item row it satisfies, keeping the
tracker consistent with what is actually on disk. The ``lesson_progress`` map
is keyed by physical lesson, because a lesson that only appears in
``additional_existing_lessons`` has no row of its own and marking that row
would falsely claim its primary was finished.

The row is found by ``proposed_topic_id``, which is how the gap analysis
recorded it, and its ``lesson_slug`` is corrected to the real slug: the
tracker's original ``proposed_slug`` was generated by slugifying the target
item name, which does not match the filename the architecture assigns.

Only ``verified`` is passed here when the caller has actually run the checks;
the script does not itself validate anything.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TRACKER = ROOT / "docs" / "M4_LESSON_REWRITE_TRACKER.json"
CONTENT = ROOT / "content"

VALIDATION_FIELDS = (
    "technical_review",
    "schema_validation",
    "mapping_validation",
    "prerequisite_validation",
    "code_validation",
    "integration_validation",
)


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    slug, topic_id = sys.argv[1], sys.argv[2]
    status = sys.argv[3] if len(sys.argv) > 3 else "verified"
    notes = sys.argv[4] if len(sys.argv) > 4 else ""

    if not (CONTENT / f"{slug}.md").exists():
        print(f"error: content/{slug}.md does not exist; refusing to mark progress")
        return 1

    data = json.loads(TRACKER.read_text(encoding="utf-8"))
    today = date.today().isoformat()

    # --- physical lesson --------------------------------------------------- #
    data.setdefault("lesson_progress", {})[slug] = {
        "rewrite_status": status,
        "last_updated": today,
        "notes": notes,
    }

    # --- target-item row --------------------------------------------------- #
    rows = [r for r in data["items"] if r.get("proposed_topic_id") == topic_id]
    if not rows:
        # already-registered topics carry the row on topic_id instead
        rows = [r for r in data["items"] if r.get("topic_id") == topic_id]
    for row in rows:
        row["lesson_slug"] = slug
        row["lesson_title"] = (CONTENT / f"{slug}.md").read_text(
            encoding="utf-8"
        ).splitlines()[0].lstrip("# ").strip()
        row["content_status"] = "existing"
        row["rewrite_status"] = status
        row["last_updated"] = today
        if notes:
            row["review_notes"] = notes
        if status == "verified":
            for field in VALIDATION_FIELDS:
                row[field] = "passed"

    TRACKER.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"marked {slug} ({topic_id}) as {status}; {len(rows)} row(s) updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
