/* Pure maths for the result views, ported from frontend/lib/viz.py.
 *
 * Every function here has a numpy counterpart in that file, and
 * scripts/golden-quantum.mts checks both against the same fixture
 * (test-fixtures/quantum-golden.json, generated by scripts/golden-quantum.py).
 * A learner reading a Bloch angle or an entropy value must get the number the
 * simulator actually implies, so these are verified rather than assumed.
 *
 * Conventions, matching the backend: amplitudes are in Qiskit order, so qubit 0
 * is the LEAST significant bit of the basis-state index (the rightmost
 * character of a bitstring).
 */

export interface Complex {
  re: number;
  im: number;
}

/** Statevector as the API sends it: [re, im] pairs. */
export type Statevector = [number, number][];

export const cx = (re: number, im: number): Complex => ({ re, im });

export const cadd = (a: Complex, b: Complex): Complex => cx(a.re + b.re, a.im + b.im);
export const cmul = (a: Complex, b: Complex): Complex =>
  cx(a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re);
export const cconj = (a: Complex): Complex => cx(a.re, -a.im);
export const cabs2 = (a: Complex): number => a.re * a.re + a.im * a.im;
export const cabs = (a: Complex): number => Math.sqrt(cabs2(a));
export const cangle = (a: Complex): number => Math.atan2(a.im, a.re);

/** Matrix type used for the 2x2 reduced density matrices. */
export type Matrix2 = [[Complex, Complex], [Complex, Complex]];

export function amplitudes(sv: Statevector | null | undefined): Complex[] | null {
  if (!sv || sv.length === 0) return null;
  // A statevector always has 2^n entries; anything else is not one.
  if ((sv.length & (sv.length - 1)) !== 0) return null;
  return sv.map(([re, im]) => cx(re, im));
}

export function qubitCount(amps: Complex[]): number {
  return Math.round(Math.log2(amps.length));
}

export function probabilities(amps: Complex[]): number[] {
  return amps.map(cabs2);
}

/** Phase relative to the first populated amplitude — a global phase is not
 *  observable, so the table shows these rather than raw angles. */
export function relativePhases(amps: Complex[]): number[] {
  const reference = amps.find((a) => cabs2(a) > 1e-12);
  const base = reference ? cangle(reference) : 0;
  return amps.map((a) => {
    let d = cangle(a) - base;
    if (d < 0) d += 2 * Math.PI;
    return d;
  });
}

/**
 * Partial trace of a pure state down to one qubit (viz.py::reduced_density_matrix).
 *
 * The numpy version reshapes to [2]*n, moves the qubit's axis to the front and
 * contracts the rest. Here the same thing is done index-wise: the row is the
 * qubit's own bit, the column is the flat index of every OTHER qubit, listed in
 * decreasing qubit order (which is what "remaining axes in increasing order"
 * means once you account for the reversed bit significance).
 */
export function reducedDensityMatrix(amps: Complex[], nQubits: number, qubit: number): Matrix2 {
  const others: number[] = [];
  for (let q = nQubits - 1; q >= 0; q -= 1) {
    if (q !== qubit) others.push(q);
  }
  const width = 1 << others.length;
  const moved: Complex[][] = [
    Array.from({ length: width }, () => cx(0, 0)),
    Array.from({ length: width }, () => cx(0, 0)),
  ];

  for (let i = 0; i < amps.length; i += 1) {
    const bit = (i >> qubit) & 1;
    let column = 0;
    for (let k = 0; k < others.length; k += 1) {
      column = (column << 1) | ((i >> others[k]) & 1);
    }
    moved[bit][column] = amps[i];
  }

  const out: Matrix2 = [
    [cx(0, 0), cx(0, 0)],
    [cx(0, 0), cx(0, 0)],
  ];
  for (let row = 0; row < 2; row += 1) {
    for (let col = 0; col < 2; col += 1) {
      let acc = cx(0, 0);
      for (let c = 0; c < width; c += 1) {
        acc = cadd(acc, cmul(moved[row][c], cconj(moved[col][c])));
      }
      out[row][col] = acc;
    }
  }
  return out;
}

/** r = (Tr(rho X), Tr(rho Y), Tr(rho Z)), via explicit Pauli products so the
 *  code reads like the textbook definition (viz.py::bloch_vector). */
export function blochVector(rho: Matrix2): [number, number, number] {
  const [[a, b], [c, d]] = rho;
  // rho @ X, X = [[0,1],[1,0]] -> trace is b + c
  const trX = cadd(b, c);
  // rho @ Y, Y = [[0,-i],[i,0]]
  const trY = cadd(cmul(b, cx(0, 1)), cmul(c, cx(0, -1)));
  // rho @ Z, Z = [[1,0],[0,-1]]
  const trZ = cadd(a, cmul(d, cx(-1, 0)));
  return [trX.re, trY.re, trZ.re];
}

/** theta from +Z (|0> = 0 deg), phi anticlockwise from +X in [0, 360). */
export function blochAngles(x: number, y: number, z: number): { theta: number; phi: number } {
  const length = Math.sqrt(x * x + y * y + z * z);
  if (length < 1e-12) return { theta: Number.NaN, phi: Number.NaN };
  const theta = (Math.acos(Math.max(-1, Math.min(1, z / length))) * 180) / Math.PI;
  const phi = (((Math.atan2(y, x) * 180) / Math.PI) % 360 + 360) % 360;
  return { theta, phi };
}

/** Eigenvalues of a 2x2 Hermitian matrix, largest first. */
export function eigenvalues2(rho: Matrix2): [number, number] {
  const [[a], [, d]] = rho;
  const trace = a.re + d.re;
  // For a 2x2 Hermitian matrix: det = a*d - |b|^2, with a and d real.
  const det = a.re * d.re - cabs2(rho[0][1]);
  const disc = Math.sqrt(Math.max(0, trace * trace - 4 * det));
  return [(trace + disc) / 2, (trace - disc) / 2];
}

/** Von Neumann entropy in bits (viz.py uses the same 1e-12 floor). */
export function entanglementEntropy(rho: Matrix2): number {
  return eigenvalues2(rho)
    .filter((l) => l > 1e-12)
    .reduce((acc, l) => acc - l * Math.log2(l), 0);
}

export function purity(rho: Matrix2): number {
  // Tr(rho^2) == sum of squared eigenvalues for a Hermitian matrix.
  return eigenvalues2(rho).reduce((acc, l) => acc + l * l, 0);
}

/** Truncated to the strongest terms, the way the tables and histogram are. */
export const SIGNIFICANT = 1e-10;

export function significantIndices(amps: Complex[]): number[] {
  const out: number[] = [];
  amps.forEach((a, i) => {
    if (cabs2(a) > SIGNIFICANT) out.push(i);
  });
  return out;
}

// ------------------------------------------------------------- formatting

/** "a + bi" with a fixed number of decimals, matching the result tables. */
export function formatAmplitude(a: Complex, places = 4): string {
  const re = a.re.toFixed(places);
  const im = Math.abs(a.im).toFixed(places);
  return `${a.re >= 0 ? "+" : ""}${re} ${a.im >= 0 ? "+" : "-"}${im}i`;
}

const trim = (value: number, places = 4): string => {
  const rounded = Number(value.toFixed(places));
  return String(rounded);
};

/** |psi> written the way a textbook writes it, e.g. "0.7071|00> + 0.7071|11>". */
export function ketExpression(
  amps: Complex[],
  maxTerms = 16,
): { expression: string; hidden: number } | null {
  const n = qubitCount(amps);
  const indices = significantIndices(amps);
  if (indices.length === 0) return null;

  const shown = indices.slice(0, maxTerms);
  const hidden = indices.length - shown.length;

  const parts = shown.map((i) => {
    const a = amps[i];
    const negative = a.re < 0 || (a.re === 0 && a.im < 0);
    let coefficient: string;
    if (Math.abs(a.im) < 1e-12) {
      coefficient = trim(Math.abs(a.re));
    } else if (Math.abs(a.re) < 1e-12) {
      coefficient = `${trim(Math.abs(a.im))}i`;
    } else {
      coefficient = `${trim(Math.abs(a.re))}${a.im > 0 ? "+" : "-"}${trim(Math.abs(a.im))}i`;
    }
    const body = coefficient === "1" ? "" : `${coefficient} `;
    return {
      sign: negative ? "-" : "+",
      term: `${body}|${i.toString(2).padStart(n, "0")}⟩`,
    };
  });

  const first = parts[0];
  let expression = (first.sign === "-" ? "-" : "") + first.term;
  for (const part of parts.slice(1)) {
    expression += ` ${part.sign} ${part.term}`;
  }
  return { expression, hidden };
}

export const formatPercent = (p: number): string => `${(p * 100).toFixed(2)}%`;
