"""Generate runnable Cirq Python scripts from the IR.

Static circuits become a pure Cirq circuit. Dynamic circuits (runtime classical
feedback) become a Cirq circuit plus a **Python driver** that implements the
if/else, for and while semantics around per-segment Cirq simulations, because
Cirq has no native runtime control flow.
"""

from __future__ import annotations

from app.quantum.ir import CircuitIR, Condition, Op

HEADER_STATIC = '''"""Generated by QuantumLearn - Cirq (static circuit)."""

import cirq
from numpy import pi

'''

HEADER_DYNAMIC = '''"""Generated by QuantumLearn - Cirq (dynamic circuit) + Python driver.

Cirq has no native runtime control flow, so classical feedback is implemented
by this driver: it simulates segment by segment, samples mid-circuit
measurements, collapses the state and then evaluates if/else, for and while
blocks in Python before continuing.
"""

import random

import cirq
import numpy as np
from numpy import pi

WHILE_CAP = 32  # hard safety cap, mirrors the platform limit


class DynamicDriver:
    """Executes a dynamic program shot-by-shot over a Cirq state vector."""

    def __init__(self, n_qubits, n_clbits, seed=None):
        self.qubits = cirq.LineQubit.range(n_qubits)
        self.n_qubits = n_qubits
        self.n_clbits = n_clbits
        self.sim = cirq.Simulator(seed=seed)
        self.rng = random.Random(seed)

    def reset_state(self):
        self.state = np.zeros(2 ** self.n_qubits, dtype=complex)
        self.state[0] = 1.0
        self.cbits = [0] * self.n_clbits

    def apply(self, circuit):
        """Evolve the current state through a unitary Cirq circuit."""
        if not len(circuit):
            return
        result = self.sim.simulate(
            circuit, qubit_order=self.qubits, initial_state=self.state.astype(np.complex64)
        )
        self.state = np.asarray(result.final_state_vector, dtype=complex)

    def measure(self, qubit_index, clbit_index):
        """Sample one qubit, collapse the state and store the classical bit."""
        axis = qubit_index  # cirq: LineQubit(0) is the most significant tensor axis
        tensor = self.state.reshape([2] * self.n_qubits)
        p1 = float(np.sum(np.abs(np.take(tensor, 1, axis=axis)) ** 2))
        outcome = 1 if self.rng.random() < p1 else 0
        keep = np.zeros_like(tensor)
        index = [slice(None)] * self.n_qubits
        index[axis] = outcome
        keep[tuple(index)] = tensor[tuple(index)]
        flat = keep.reshape(-1)
        norm = np.linalg.norm(flat)
        if norm == 0:
            outcome = 1 - outcome
            keep = np.zeros_like(tensor)
            index[axis] = outcome
            keep[tuple(index)] = tensor[tuple(index)]
            flat = keep.reshape(-1)
            norm = np.linalg.norm(flat) or 1.0
        self.state = flat / norm
        self.cbits[clbit_index] = outcome
        return outcome

    def reset_qubit(self, qubit_index):
        if self.measure(qubit_index, 0) == 1:
            c = cirq.Circuit(cirq.X(self.qubits[qubit_index]))
            self.apply(c)

    def bitstring(self):
        # qubit 0 as the rightmost character (Qiskit convention)
        return "".join(str(b) for b in reversed(self.cbits))

'''


def generate(ir: CircuitIR, shots: int = 1024) -> str:
    return generate_dynamic(ir, shots) if ir.is_dynamic() else generate_static(ir, shots)


# --------------------------------------------------------------------------- #
# Static
# --------------------------------------------------------------------------- #
def generate_static(ir: CircuitIR, shots: int = 1024) -> str:
    lines = [
        HEADER_STATIC,
        f"qubits = cirq.LineQubit.range({ir.n_qubits})",
        "circuit = cirq.Circuit()",
        "",
    ]
    measured: list[int] = []
    for op in sorted(ir.ops, key=lambda o: o.layer):
        lines.extend(_emit_static(op, measured))
    if not measured:
        measured = list(range(ir.n_qubits))
        lines.append("# no explicit measurements; measuring all qubits")
    args = ", ".join(f"qubits[{q}]" for q in sorted(set(measured)))
    lines += [
        f'circuit.append(cirq.measure({args}, key="m"))',
        "",
        "result = cirq.Simulator().run(circuit, repetitions=%d)" % shots,
        'print(result.histogram(key="m"))',
        "",
    ]
    return "\n".join(lines)


def _emit_static(op: Op, measured: list[int]) -> list[str]:
    if op.kind == "gate":
        return [f"circuit.append({_cirq_gate(op)})"]
    if op.kind == "measure":
        measured.append(op.qubits[0])
        return []
    if op.kind == "reset":
        return [f"circuit.append(cirq.ResetChannel().on(qubits[{q}]))" for q in op.qubits]
    if op.kind == "barrier":
        return ["# barrier (no Cirq equivalent)"]
    if op.kind == "for":
        out = [f"for _ in range({op.loop_n or 0}):"]
        body = [ln for child in op.body for ln in _emit_static(child, measured)]
        return out + ["    " + ln for ln in (body or ["pass"])]
    if op.kind == "box":
        out = [f"# --- box: {op.box_name} ---"]
        for child in op.body:
            out += _emit_static(child, measured)
        return out + [f"# --- end box: {op.box_name} ---"]
    return [f"# unsupported static op: {op.kind}"]


def _cirq_gate(op: Op) -> str:
    name = op.gate or "id"
    params = [p.expr for p in op.params]
    targets = [f"qubits[{q}]" for q in op.qubits]
    controls = [f"qubits[{q}]" for q in op.controls]

    base = {
        "h": "cirq.H",
        "x": "cirq.X",
        "y": "cirq.Y",
        "z": "cirq.Z",
        "id": "cirq.I",
        "s": "cirq.S",
        "sdg": "(cirq.S ** -1)",
        "t": "cirq.T",
        "tdg": "(cirq.T ** -1)",
        "sx": "(cirq.X ** 0.5)",
        "swap": "cirq.SWAP",
    }
    if name in {"rx", "ry", "rz"}:
        expr = f"cirq.{name}({params[0]})"
    elif name == "p":
        expr = f"cirq.ZPowGate(exponent=({params[0]}) / pi)"
    else:
        expr = base.get(name, "cirq.I")

    if controls:
        return f"{expr}.on({', '.join(targets)}).controlled_by({', '.join(controls)})"
    return f"{expr}.on({', '.join(targets)})"


# --------------------------------------------------------------------------- #
# Dynamic (circuit + Python driver)
# --------------------------------------------------------------------------- #
def generate_dynamic(ir: CircuitIR, shots: int = 1024) -> str:
    lines = [HEADER_DYNAMIC]
    lines += [
        f"N_QUBITS = {ir.n_qubits}",
        f"N_CLBITS = {ir.n_clbits}",
        f"SHOTS = {shots}",
        "",
        "",
        "def run_shot(d):",
        "    \"\"\"Execute one shot of the dynamic program.\"\"\"",
        "    d.reset_state()",
        "    q = d.qubits",
    ]
    body = [ln for op in sorted(ir.ops, key=lambda o: o.layer) for ln in _emit_dynamic(op, 1)]
    lines += body or ["    pass"]
    lines += [
        "    return d.bitstring()",
        "",
        "",
        "if __name__ == '__main__':",
        "    driver = DynamicDriver(N_QUBITS, N_CLBITS, seed=None)",
        "    counts = {}",
        "    for _ in range(SHOTS):",
        "        key = run_shot(driver)",
        "        counts[key] = counts.get(key, 0) + 1",
        "    print(dict(sorted(counts.items())))",
        "",
    ]
    return "\n".join(lines)


def _emit_dynamic(op: Op, indent: int) -> list[str]:  # noqa: C901 - emitter dispatch
    pad = "    " * indent
    kind = op.kind

    if kind == "gate":
        return [f"{pad}d.apply(cirq.Circuit({_cirq_gate_q(op)}))"]
    if kind == "measure":
        c = op.clbits[0] if op.clbits else op.qubits[0]
        return [f"{pad}d.measure({op.qubits[0]}, {c})"]
    if kind == "reset":
        return [f"{pad}d.reset_qubit({q})" for q in op.qubits]
    if kind == "barrier":
        return [f"{pad}# barrier"]

    if kind == "if":
        out = [f"{pad}if {_py_condition(op.condition)}:"]
        body = [ln for child in op.body for ln in _emit_dynamic(child, indent + 1)]
        out += body or [f"{pad}    pass"]
        if op.else_body:
            out.append(f"{pad}else:")
            out += [ln for child in op.else_body for ln in _emit_dynamic(child, indent + 1)]
        return out

    if kind == "for":
        out = [f"{pad}for _ in range({op.loop_n or 0}):"]
        body = [ln for child in op.body for ln in _emit_dynamic(child, indent + 1)]
        return out + (body or [f"{pad}    pass"])

    if kind == "while":
        guard = f"_i{indent}"
        out = [
            f"{pad}{guard} = 0",
            f"{pad}while {_py_condition(op.condition)} and {guard} < WHILE_CAP:",
        ]
        body = [ln for child in op.body for ln in _emit_dynamic(child, indent + 1)]
        out += body or [f"{pad}    pass"]
        out.append(f"{pad}    {guard} += 1")
        return out

    if kind == "box":
        out = [f"{pad}# --- box: {op.box_name} ---"]
        for child in op.body:
            out += _emit_dynamic(child, indent)
        return out + [f"{pad}# --- end box: {op.box_name} ---"]

    return [f"{pad}# unsupported op: {kind}"]


def _cirq_gate_q(op: Op) -> str:
    """Same as _cirq_gate but against the driver's ``q`` qubit list."""
    return _cirq_gate(op).replace("qubits[", "q[")


def _py_condition(cond: Condition | None) -> str:
    if cond is None or cond.type == "true":
        return "True"
    if cond.type == "bit_eq":
        return f"d.cbits[{cond.bit}] == {1 if cond.value is None else cond.value}"
    start = 0 if cond.start is None else cond.start
    end = start + 1 if cond.end is None else cond.end
    value = cond.value
    if isinstance(value, int):
        value = format(value, f"0{end - start}b")
    joined = f"''.join(str(b) for b in d.cbits[{start}:{end}])"
    return f'{joined} == "{value}"'


__all__ = ["generate", "generate_static", "generate_dynamic"]
