"""Generate runnable qBraid submission scripts from the IR.

qBraid is a job-submission service rather than a local simulator, so the
generated program is a *client*: it builds the circuit as OpenQASM 3, submits
it to a device, polls until the job reaches a terminal state and prints the
counts. This mirrors what ``backend/app/quantum/backends/qbraid_sim.py`` does
at runtime, so the exported script reproduces the app's behaviour.

Static circuits only, matching the executable backend.
"""

from __future__ import annotations

from app.quantum.ir import CircuitIR
from app.quantum.qasm3_codec import to_qasm3

DYNAMIC_NOTE = '''"""Generated by QuantumLearn - qBraid.

This circuit uses runtime classical control flow (if/else, while, or a
mid-circuit measurement that later operations depend on).

The platform runs dynamic circuits on the Qiskit dynamic engine only. qBraid
devices here accept static OpenQASM 3, so no submission script is emitted:
it would be rejected or would silently run different semantics.

To run this circuit as code, use the **Qiskit** export tab.
"""
'''

TEMPLATE = '''"""Generated by QuantumLearn - qBraid submission script.

Submits the circuit below to a qBraid device, waits for the job to finish and
prints the measurement counts.

Before running:

    pip install qbraid
    export QBRAID_API_KEY=...        # your qBraid API key
    export QBRAID_DEVICE_ID={device}

Free public simulators (0 credits) include:
    qbraid_qir_simulator, ionq:ionq:sim:simulator, rigetti:qvm
Real QPUs consume credits -- check pricing before switching DEVICE_ID.
"""

import os

from qbraid.runtime import QbraidProvider

QASM3 = """\\
{qasm}"""

SHOTS = {shots}
DEVICE_ID = os.environ.get("QBRAID_DEVICE_ID", "{device}")


def main():
    api_key = os.environ.get("QBRAID_API_KEY")
    if not api_key:
        raise SystemExit("Set QBRAID_API_KEY first.")

    provider = QbraidProvider(api_key=api_key)
    device = provider.get_device(DEVICE_ID)

    print(f"Submitting to {{DEVICE_ID}} ({{SHOTS}} shots)...")
    job = device.run(QASM3, shots=SHOTS)
    print(f"Job id: {{job.id}}")

    # Blocks until the job reaches a terminal state.
    job.wait_for_final_state()
    if not job.is_terminal_state():
        raise SystemExit(f"Job did not finish: {{job.status()}}")

    result = job.result()
    counts = result.data.get_counts()
    print(dict(sorted(counts.items())))


if __name__ == "__main__":
    main()
'''


def generate(ir: CircuitIR, shots: int = 1024, device: str = "qbraid_qir_simulator") -> str:
    if ir.is_dynamic():
        return DYNAMIC_NOTE
    qasm = to_qasm3(ir)
    if not qasm.endswith("\n"):
        qasm += "\n"
    return TEMPLATE.format(qasm=qasm, shots=shots, device=device)


__all__ = ["generate"]
