"""Generate runnable PennyLane Python scripts from the IR.

PennyLane describes a circuit as a *QNode*: a Python function decorated with a
device. Gates are applied as side effects inside that function and the return
value declares what to measure.

Static circuits only. PennyLane's ``default.qubit`` supports mid-circuit
measurement, but the platform routes dynamic circuits to the Qiskit dynamic
engine, so exporting a half-supported dynamic script would misrepresent what
actually runs. Dynamic circuits get an explanatory script instead.
"""

from __future__ import annotations

from app.quantum.ir import CircuitIR, Op

HEADER = '''"""Generated by QuantumLearn - PennyLane (static circuit)."""

import pennylane as qml
from numpy import pi

'''

DYNAMIC_NOTE = '''"""Generated by QuantumLearn - PennyLane.

This circuit uses runtime classical control flow (if/else, while, or a
mid-circuit measurement that later operations depend on).

The platform executes dynamic circuits on the Qiskit dynamic engine, not on
PennyLane, so no PennyLane script is emitted here: it would not reproduce the
behaviour you saw in the app.

To run this circuit as code, use the **Qiskit** export tab.
"""
'''


def generate(ir: CircuitIR, shots: int = 1024) -> str:
    if ir.is_dynamic():
        return DYNAMIC_NOTE
    return generate_static(ir, shots)


def generate_static(ir: CircuitIR, shots: int = 1024) -> str:
    measured: list[int] = []
    body: list[str] = []
    for op in sorted(ir.ops, key=lambda o: o.layer):
        body.extend(_emit(op, measured, indent=1))

    if not measured:
        measured = list(range(ir.n_qubits))
        body.append("    # no explicit measurements; sampling all wires")

    wires = sorted(set(measured))
    wire_list = ", ".join(str(w) for w in wires)

    lines = [
        HEADER,
        f"N_WIRES = {ir.n_qubits}",
        f"SHOTS = {shots}",
        "",
        'dev = qml.device("default.qubit", wires=N_WIRES, shots=SHOTS)',
        "",
        "",
        "@qml.qnode(dev)",
        "def circuit():",
    ]
    lines += body or ["    pass"]
    lines += [
        f"    return qml.counts(wires=[{wire_list}])",
        "",
        "",
        "if __name__ == '__main__':",
        "    print(circuit())",
        "",
    ]
    return "\n".join(lines)


def _emit(op: Op, measured: list[int], indent: int) -> list[str]:
    pad = "    " * indent
    kind = op.kind

    if kind == "gate":
        return [pad + _pl_gate(op)]
    if kind == "measure":
        # Terminal measurement: recorded and emitted by the QNode's return.
        measured.append(op.qubits[0])
        return []
    if kind == "reset":
        # No reset op on default.qubit; the platform blocks dynamic circuits
        # from this exporter, so a mid-circuit reset cannot be represented.
        return [f"{pad}# reset on wire {q} is not supported by default.qubit" for q in op.qubits]
    if kind == "barrier":
        return [f"{pad}qml.Barrier(wires={list(op.qubits) or 'None'})"]
    if kind == "for":
        out = [f"{pad}for _ in range({op.loop_n or 0}):"]
        body = [ln for child in op.body for ln in _emit(child, measured, indent + 1)]
        return out + (body or [f"{pad}    pass"])
    if kind == "box":
        out = [f"{pad}# --- box: {op.box_name} ---"]
        for child in op.body:
            out += _emit(child, measured, indent)
        return out + [f"{pad}# --- end box: {op.box_name} ---"]
    return [f"{pad}# unsupported static op: {kind}"]


def _pl_gate(op: Op) -> str:
    """Render one gate.

    PennyLane has no generic control modifier on every operation, so a
    controlled gate is emitted as ``qml.ctrl(qml.Gate, control=[...])``, which
    works uniformly for arbitrary control counts (including MCX).
    """
    name = op.gate or "id"
    params = [p.expr for p in op.params]
    targets = list(op.qubits)
    controls = list(op.controls)

    simple = {
        "h": "Hadamard",
        "x": "PauliX",
        "y": "PauliY",
        "z": "PauliZ",
        "id": "Identity",
        "s": "S",
        "t": "T",
        "sx": "SX",
        "swap": "SWAP",
    }
    adjoint = {"sdg": "S", "tdg": "T"}
    rotations = {"rx": "RX", "ry": "RY", "rz": "RZ", "p": "PhaseShift"}

    wires = targets[0] if len(targets) == 1 else targets

    if name in rotations:
        inner = f"qml.{rotations[name]}({params[0]}, wires={wires})"
        ctrl_cls = f"qml.{rotations[name]}"
        ctrl_args = f"({params[0]}, wires={wires})"
    elif name in adjoint:
        inner = f"qml.adjoint(qml.{adjoint[name]}(wires={wires}))"
        ctrl_cls = None
        ctrl_args = ""
    else:
        cls = simple.get(name, "Identity")
        inner = f"qml.{cls}(wires={wires})"
        ctrl_cls = f"qml.{cls}"
        ctrl_args = f"(wires={wires})"

    if not controls:
        return inner

    control_arg = controls[0] if len(controls) == 1 else controls
    if ctrl_cls is None:
        # adjoint(S)/adjoint(T) under control: wrap the built operator
        return f"qml.ctrl({inner}, control={control_arg})"
    return f"qml.ctrl({ctrl_cls}, control={control_arg}){ctrl_args}"


__all__ = ["generate", "generate_static"]
