"""Generate runnable Qiskit Python scripts from the IR (static and dynamic)."""

from __future__ import annotations

from app.quantum.ir import CircuitIR, Condition, Op

HEADER_STATIC = '''"""Generated by QuantumLearn - Qiskit (static circuit)."""

from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator
from numpy import pi

'''

HEADER_DYNAMIC = '''"""Generated by QuantumLearn - Qiskit (dynamic circuit).

Uses Qiskit control-flow builders (if_test / for_loop / while_loop). Run on a
backend that supports dynamic circuits, e.g. AerSimulator.
"""

from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator
from numpy import pi

WHILE_CAP = 32  # platform safety cap on while-loop iterations

'''


def generate(ir: CircuitIR, shots: int = 1024) -> str:
    return generate_dynamic(ir, shots) if ir.is_dynamic() else generate_static(ir, shots)


def generate_static(ir: CircuitIR, shots: int = 1024) -> str:
    lines = [HEADER_STATIC, f"qc = QuantumCircuit({ir.n_qubits}, {ir.n_clbits})", ""]
    for op in sorted(ir.ops, key=lambda o: o.layer):
        lines.extend(_emit(op, indent=0))
    lines += [
        "",
        "sim = AerSimulator()",
        "compiled = transpile(qc, sim)",
        f"result = sim.run(compiled, shots={shots}).result()",
        "print(result.get_counts())",
        "",
    ]
    return "\n".join(lines)


def generate_dynamic(ir: CircuitIR, shots: int = 1024) -> str:
    lines = [HEADER_DYNAMIC, f"qc = QuantumCircuit({ir.n_qubits}, {ir.n_clbits})", ""]
    for op in sorted(ir.ops, key=lambda o: o.layer):
        lines.extend(_emit(op, indent=0))
    lines += [
        "",
        "sim = AerSimulator()",
        "compiled = transpile(qc, sim)",
        f"result = sim.run(compiled, shots={shots}).result()",
        "print(result.get_counts())",
        "",
    ]
    return "\n".join(lines)


def _emit(op: Op, indent: int) -> list[str]:  # noqa: C901 - emitter dispatch
    pad = "    " * indent
    kind = op.kind

    if kind == "gate":
        return [pad + _emit_gate(op)]
    if kind == "measure":
        c = op.clbits[0] if op.clbits else op.qubits[0]
        return [f"{pad}qc.measure({op.qubits[0]}, {c})"]
    if kind == "reset":
        return [f"{pad}qc.reset({q})" for q in op.qubits]
    if kind == "barrier":
        args = ", ".join(str(q) for q in op.qubits)
        return [f"{pad}qc.barrier({args})"]

    if kind == "if":
        cond = _emit_condition(op.condition)
        out = [f"{pad}with qc.if_test({cond}) as _else:"]
        body = [ln for child in op.body for ln in _emit(child, indent + 1)]
        out += body or [f"{pad}    pass"]
        if op.else_body:
            out.append(f"{pad}with _else:")
            out += [ln for child in op.else_body for ln in _emit(child, indent + 1)]
        return out

    if kind == "for":
        out = [f"{pad}with qc.for_loop(range({op.loop_n or 0})):"]
        body = [ln for child in op.body for ln in _emit(child, indent + 1)]
        return out + (body or [f"{pad}    pass"])

    if kind == "while":
        cond = _emit_condition(op.condition)
        out = [f"{pad}# platform caps this loop at WHILE_CAP iterations", f"{pad}with qc.while_loop({cond}):"]
        body = [ln for child in op.body for ln in _emit(child, indent + 1)]
        return out + (body or [f"{pad}    pass"])

    if kind == "box":
        out = [f"{pad}# --- box: {op.box_name} ---"]
        out += [ln for child in op.body for ln in _emit(child, indent)]
        out.append(f"{pad}# --- end box: {op.box_name} ---")
        return out

    return [f"{pad}# unsupported op: {kind}"]


def _emit_gate(op: Op) -> str:
    name = op.gate or "id"
    params = [p.expr.replace("pi", "pi") for p in op.params]
    targets = list(op.qubits)
    controls = list(op.controls)

    if name == "x" and controls:
        if len(controls) == 1:
            return f"qc.cx({controls[0]}, {targets[0]})"
        if len(controls) == 2:
            return f"qc.ccx({controls[0]}, {controls[1]}, {targets[0]})"
        return f"qc.mcx({controls}, {targets[0]})"

    if controls:
        simple = {"z": "cz", "y": "cy", "p": "cp", "rz": "crz", "rx": "crx", "ry": "cry"}
        if len(controls) == 1 and name in simple:
            args = ", ".join(params + [str(controls[0]), str(targets[0])])
            return f"qc.{simple[name]}({args})"
        if len(controls) == 1 and name == "swap":
            return f"qc.cswap({controls[0]}, {targets[0]}, {targets[1]})"
        gate_expr = _gate_object(name, params)
        qargs = controls + targets
        return f"qc.append({gate_expr}.control({len(controls)}), {qargs})"

    arglist = ", ".join(params + [str(q) for q in targets])
    return f"qc.{name}({arglist})"


def _gate_object(name: str, params: list[str]) -> str:
    classes = {
        "h": "HGate",
        "x": "XGate",
        "y": "YGate",
        "z": "ZGate",
        "id": "IGate",
        "s": "SGate",
        "sdg": "SdgGate",
        "t": "TGate",
        "tdg": "TdgGate",
        "sx": "SXGate",
        "swap": "SwapGate",
        "p": "PhaseGate",
        "rx": "RXGate",
        "ry": "RYGate",
        "rz": "RZGate",
    }
    cls = classes.get(name, "IGate")
    return f"__import__('qiskit.circuit.library', fromlist=['{cls}']).{cls}({', '.join(params)})"


def _emit_condition(cond: Condition | None) -> str:
    if cond is None or cond.type == "true":
        return "(None, True)"
    if cond.type == "bit_eq":
        return f"(qc.clbits[{cond.bit}], {1 if cond.value is None else cond.value})"
    start = 0 if cond.start is None else cond.start
    end = start + 1 if cond.end is None else cond.end
    value = cond.value
    if isinstance(value, str):
        value = int(value, 2)
    bits = list(range(start, end))
    return f"(__import__('qiskit').circuit.classical.expr.lift(qc.cregs[0]), {value})  # bits {bits}"


__all__ = ["generate", "generate_static", "generate_dynamic"]
